name: Generate Binaries

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Show toolchain
      run: rustup show

    - name: Install musl toolchain
      run: rustup target add x86_64-unknown-linux-musl

    - name: Build
      run: cargo build --release --verbose --target=x86_64-unknown-linux-musl --bin librarian --bin server
      
    - uses: actions/upload-artifact@v2
      name: Save Librarian cli
      with:
        name: librarian
        path: target/x86_64-unknown-linux-musl/release/librarian

    - uses: actions/upload-artifact@v2
      name: Save server
      with:
        name: librarian-server
        path: target/x86_64-unknown-linux-musl/release/server
